name: Deploy App to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. 시크릿에 저장된 프로젝트 경로로 이동
            cd ${{ secrets.DOTNET_APP_PATH }}

            # 2. git pull 명령으로 최신 소스 코드를 가져옴
            echo "Pulling latest source code..."
            git pull

            # 3. myapp.service 재시작 (ec2.sh 스크립트 실행 트리거)
            echo "Restarting application service to trigger build and run..."
            sudo systemctl restart myapp.service

            echo "Deployment triggered successfully!"