name: Deploy .NET App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. 시크릿에 저장된 프로젝트 경로로 이동
            cd ${{ secrets.DOTNET_APP_PATH }}

            # 2. git pull 명령으로 최신 소스 코드를 가져옴
            echo "Pulling latest source code..."
            git pull

            # 3. 서버에서 직접 publish 실행 (배포용 빌드)
            echo "Publishing the application on the server..."
            dotnet publish --configuration Release -o publish

            # 4. 백그라운드 서비스 재시작
            echo "Restarting application service..."
            sudo systemctl restart myapp.service

            echo "Deployment successful!"